WIP: capture backtraces and report them along with full cycle information
bertptrs/tracing-mutex pull request #28
Opened 2022-10-27 22:35 UTC by tbodt

2022-12-16 18:54 UTC, tbodt commented
Would like to merge this, @bertptrs. I'll need to rewrite the commit messages :P but otherwise I think this is ready to review.

2022-12-17 20:57 UTC, bertptrs commented
Hey, thank you for the PR! This is sort of what I had in mind when I got started on the crate, nice to see it actually in code.

I will have a look at this. One concern from an initial look is that capturing the traces all around might reduce performance by a lot. This is all speculation of course; I'll need to have a deeper look to be sure.

If it does end up affecting performance, that doesn't even mean we cannot include it; we'd simply have to feature-gate it.

2022-12-18 00:32 UTC, tbodt commented
It does in fact reduce performance by a lot. The second commit reduces the performance hit, so the cost is on the order of the number of locks rather than the number of lock operations. It's still significant for the kind of program that constantly creates and destroys locks.

I haven't found it necessary to feature gate it because RUST_LIB_BACKTRACE is an effective control. But a feature could make sense.

2023-02-19 12:51 UTC, bertptrs requested changes
Hey, sorry that I left this for so long. Life got in the way.

I left some design-wise comments below.

I'd also like to ask you to fix the compilation issues and clippy problems. In particular, you introduced quite a few needless explicit returns. Could you address those as well the comments?

2023-02-19 12:51 UTC, bertptrs commented on src/graph.rs
> +        assert_eq!(graph.add_edge(1, 1, ()), Err(vec![(1, ())]));
The tests do not compile since you later changed the `add_edge` signature to take an `FnOnce` rather than a value.

2023-02-19 12:51 UTC, bertptrs commented on src/graph.rs
> +        cycle: &mut Vec<(V, V, E)>,
Doesn't it make more sense to have this function return `Result<(), Vec<(V, V, E)>>` instead?

2023-02-19 12:51 UTC, bertptrs commented on src/graph.rs
> +            } else if !visited.contains(&w) && ord < ub {
This is not your doing, but if we're changing the line anyway, we could optimize it to

```suggestion
            } else if ord < ub && visited.insert(w) {
```

and save a hash operation on insertion

2023-02-19 12:51 UTC, bertptrs commented on src/lib.rs
> +        MutexEdge(Arc::new(Backtrace::capture()))
`Backtrace::capture` is a no-op by default. Does it make sense to force capturing the backtrace anyway depending on `debug_assertions`?

2023-09-09 09:40 UTC, bertptrs commented
Obsoleted by #32. Thank you for your contribution.

2023-09-09 09:40 UTC, closed without merging